# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-25 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snack_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='amount_used',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='expiration',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='max_inventory',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='min_inventory',
            field=models.IntegerField(blank=True),
        ),
    ]
