# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-25 22:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snack_app', '0003_items_buy_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='buy_group',
        ),
        migrations.AddField(
            model_name='items',
            name='buy_group',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='snack_app.BuyGroup'),
            preserve_default=False,
        ),
    ]
