# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-25 23:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snack_app', '0004_auto_20180425_2248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='amount_used',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='expiration',
        ),
        migrations.AddField(
            model_name='inventory',
            name='buy_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='snack_app.BuyGroup'),
            preserve_default=False,
        ),
    ]
