# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-27 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snack_app', '0007_auto_20180427_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='picture',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
